:truck: rename some scripts
Former-commit-id: 0b687c2eef300882b45c4e1996d092263860a4f1

diff --git a/private_dot_local/bin/executable_shmoji b/private_dot_local/bin/executable_shmoji
--- a/private_dot_local/bin/executable_shmoji
+++ b/private_dot_local/bin/executable_shmoji
@@ -15,54 +15,54 @@ emojidir="$HOME/.cache/shmoji"
 emojifile="$emojidir/emojis.txt"
 
 die() {
-    printf "%s\n" "$1"
-    exit 1
+	printf "%s\n" "$1"
+	exit 1
 }
 
 depends() {
-    for dep in "$@"; do
-        command -v "$dep" > /dev/null || die "$dep not found"
-    done
+	for dep in "$@"; do
+		command -v "$dep" >/dev/null || die "$dep not found"
+	done
 }
 
 emojicheck() {
-    [ -f "$emojifile" ] || die "emojis not found. try 'shmoji download'"
+	[ -f "$emojifile" ] || die "emojis not found. try 'shmoji download'"
 }
 
 emojiprint() {
-    printf "%s" "$1" | cut -d " " -f 1 | tr -d '\n'
+	printf "%s" "$1" | cut -d " " -f 1 | tr -d '\n'
 }
 
 case "$cmd" in
-    download)
-        depends curl
-        mkdir -p "$emojidir"
-        # $ wc -l /var/www/trash.j3s.sh/emojis.txt 
-        # 3570 /var/www/trash.j3s.sh/emojis.txt
-        curl 'https://trash.j3s.sh/emojis.txt' >"$emojifile"
-        ;;
-    bemenu)
-        emojicheck
-        depends bemenu wtype
-        emoji=$(cat "$emojifile" | bemenu -l 20)
-        emojiprint "$emoji" | wtype -
-        ;;
-    rofi)
-        emojicheck
-        depends rofi xdotool
-        win=$(xdotool getactivewindow)
-        emoji=$(cat "$emojifile" | rofi -dmenu | cut -d " " -f 1 | tr -d '\n')
-        [ "$emoji" ] && xdotool windowactivate --sync $win type --clearmodifiers $emoji
-        ;;
-    fzf)
-        emojicheck
-        depends fzf
-        emoji=$(cat "$emojifile" | fzf)
-        emojiprint "$emoji"
-        ;;
-    *)
-        printf "%s\n" "usage: shmoji [download | bemenu | rofi | fzf]"
-        ;;
+download)
+	depends curl
+	mkdir -p "$emojidir"
+	# $ wc -l /var/www/trash.j3s.sh/emojis.txt
+	# 3570 /var/www/trash.j3s.sh/emojis.txt
+	curl 'https://trash.j3s.sh/emojis.txt' >"$emojifile"
+	;;
+bemenu)
+	emojicheck
+	depends bemenu wtype
+	emoji=$(cat "$emojifile" | bemenu -l 20)
+	emojiprint "$emoji" | wtype -
+	;;
+rofi)
+	emojicheck
+	depends rofi xdotool
+	win=$(xdotool getactivewindow)
+	emoji=$(cat "$emojifile" | rofi -dmenu | cut -d " " -f 1 | tr -d '\n')
+	[ "$emoji" ] && xdotool windowactivate --sync $win type --clearmodifiers $emoji
+	;;
+fzf)
+	emojicheck
+	depends fzf
+	emoji=$(cat "$emojifile" | fzf)
+	emojiprint "$emoji"
+	;;
+*)
+	printf "%s\n" "usage: shmoji [download | bemenu | rofi | fzf]"
+	;;
 esac
 
 exit 0
